import "./globals.css";
import { Footer } from "@/components/central-site/footer";
import { Inter } from "next/font/google";
import ReduxProvider from "@/reduxStore/provider";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
    >
      <body className="lg:h-screen h-full flex flex-col">
        <main className="grow">
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </main>
        <Footer />
      </body>
    </html>
  );
}
